<?php

	$indexArray = array('title' => ' Third Eye Infosystems | Web Design Company | Web Development Company | Digital Marketing Company' ,'desc' => 'Third Eye Infosystems is an international web design and web development company in Bangalore, India. Our team expertise in website design & development service, mobile app development, and digital marketing. Contact us now!', 'keyword' => 'Web development company in India, Web design company, web design and development services, Web development company in Bangalore, Web design company in Bangalore, Web design agency in India, Mobile app development company in India, Mobile app design company in Bangalore' );
	$aboutusArray = array('title' => ' About Third Eye Infosystems | Web Design and Development Company | Digital Marketing Agency' ,'desc' => 'Third Eye Infosystems is an international web design and web development company in Bangalore, India. Our team expertise in website design & development service, mobile app development, and digital marketing. Contact us now!', 'keyword' => 'Web development company in India, Web design company, web design and development services, Web development company in Bangalore, Web design company in Bangalore, Web design agency in India, Mobile app development company in India, Mobile app design company in Bangalore' );

$contactusArray = array('title' => ' Contact Third Eye Infosystems | Web Design and Development Company | Digital Marketing Agency' ,'desc' => 'Contact us today. for website design & development service, mobile app development, and digital marketing. Contact us now!', 'keyword' => 'Web design company in India, Web design company, web design and development services, Web development company in Bangalore, Web design company in Bangalore, Web design agency in India, Mobile app development company in India, Mobile app design company in Bangalore' );

	$webservicesArray = array('title' => ' Web design and development company Bangalore | Web design company Bangalore | Web development company Bangalore' ,'desc' => 'Leading Web Development Company in Bangalore, Web Designing Company in Bangalore, Web Design Company in Bangalore, Web development company near me, Web Designing Services in Bangalore, Website Development Services Bangalore, Web Design Agency in Bangalore', 'keyword' => 'Web development company in Bangalore, Web design company in Bangalore, Web development services in Bangalore, Web design services in Bangalore, Web development agency in Bangalore, Web design agency in Bangalore, Web development company near me');
	$websitedesignArray = array('title' => ' Web Design Company | Website Design Company | Web Design Services' ,'desc' => 'Third Eye Infosystems - Web design company, is one of the best web design company in Bangalore. We deliver the imagination into reality with our top notch website designing services.', 'keyword' => 'Web design company, website design company, web design services, web design company bangalore, website designing company in bangalore, web designing agency, web design company near me, web designers in bangalore, web design companies bangalore');
	$websitedevelopmentArray = array('title' => ' Web Development Company | Web Development Companies | Web Development Services' ,'desc' => 'Third Eye Infosystems is one of the best web development company in Bangalore. We deliver cutting edge websites with our top notch web development services.', 'keyword' => 'Web development company, web development company in bangalore, web development agency, website development company, web development company near me, web development services, website development agency bangalore, Website Development Companies in Bangalore.');
	$ecommercewebsitedevelopmentArray = array('title' => ' Ecommerce Website Development Company | Ecommerce Web development Company Bangalore' ,'desc' => 'We are a custom ecommerce website development company in Bangalore, India. We cater ecommerce website development in various platforms like Magento, Opencart, Shopify, Codeigniter, Woocommerce and more. Hire best ecommerce website design and development company in Bangalore, India.', 'keyword' => 'Ecommerce Website Development Company, Ecommerce Web Development Services, best ecommerce website developers in india, ecommerce website development company in bangalore, magento development company in bangalore, ecommerce web development services in bangalore, ecommerce web development agency, eCommerce Companies in Bangalore, Ecommerce Website Maintenance and Support');
	$cmswebsitedevelopmentArray = array('title' => ' CMS Website Development Company | CMS Website Development Services' ,'desc' => 'Third Eye Infosystems - CMS Website development company, is one of the best CMS website development company in Bangalore. Hire best CMS website design and development company in Bangalore, India.', 'keyword' => 'cms website development company, cms web design and development company, cms website design company, cms website development companies, custom cms development, cms for custom website.');
	$landingpagedevelopmentArray = array('title' => ' Landing Page Development Company | Landing Page Development Services' ,'desc' => 'As a best landing page development company we create effective and relevant landing pages which helps in more visitor traction and to increase sales. Hire our landing page development services.', 'keyword' => 'Landing page development company, landing page development services, landing page development company in bangalore, landing page design and development services, landing page design services.', 'meta1' => 'name="robots" content="noindex"', 'meta2' => 'name="robots" content="noindex"');

	$mobileappdevelopmentArray = array('title' => 'Mobile App Development Services | Mobile App Development Company' ,'desc' => 'Get an advanced mobile app from our best mobile app development services. We are the most trusted mobile app development company in Bangalore.', 'keyword' => 'Mobile App development company, mobile app development services, mobile app development agency, app development companies, mobile app development near me, mobile app development company in India, Mobile app development company in Bangalore, app development services, app development agency.');
	$androidappdevelopmentArray = array('title' => 'Android App Development Company | Android App Developers' ,'desc' => 'Third Eye Infosystems is a preferred android app development company that has been playing an influential role in this respective industry to render customized solutions. Hire best android development company in Bangalore.', 'keyword' => ' Android app development company, android apps development services, android app development company near me, android app developers in bangalore, best android app development company, android app developers near me.');
	$iosappdevelopmentArray = array('title' => 'iOS App Development Company | iOS App Development Services' ,'desc' => 'Third Eye Infosystems is a full-service iOS app development company that offers feature-rich, elegant, and custom IOS applications. Hire the best iOS app development service provider.', 'keyword' => 'ios app development company, ios app development services, ios application development company, ios app design and development company, best ios app development company, ios app development company in INDIA, iOS app development company in Bangalore.');
	$digitalmarketingservicesArray = array('title' => 'Digital Marketing Agency | Digital Marketing Services | Digital Marketing Company' ,'desc' => 'Work with the best digital marketing agency. With our renowned digital marketing services, increase web traffic, leads and sales. Lets grow your business.', 'keyword' => 'Digital marketing services, Digital marketing agency, Digital marketing company, best digital marketing services, digital marketing services india, digital marketing services in bangalore, digital marketing services near me, digital marketing services company, digital marketing company in bangalore.');
	$Array = array('title' => '' ,'description' => '' );
	$Array = array('title' => '' ,'description' => '' );
	$Array = array('title' => '' ,'description' => '' );
	$Array = array('title' => '' ,'description' => '' );
	$Array = array('title' => '' ,'description' => '' );
	$Array = array('title' => '' ,'description' => '' );
	$metaArray = array('index' => $indexArray, 'about-us' => $aboutusArray, 'web-services' => $webservicesArray, 'website-design' => $websitedesignArray, 'website-development' => $websitedevelopmentArray, 'ecommerce-website-development' => $ecommercewebsitedevelopmentArray, 'cms-website-development' => $cmswebsitedevelopmentArray, 'landing-page-development' => $landingpagedevelopmentArray, 'mobile-app-development' => $mobileappdevelopmentArray, 'android-app-development' => $androidappdevelopmentArray, 'ios-app-development' => $iosappdevelopmentArray, 'digital-marketing-services' => $digitalmarketingservicesArray, 'contact-us' => $contactusArray,); 